---

- name: "Install dovecot and pigeonhole packages"
  loop:
    - dovecot
    - dovecot-pigeonhole
  package:
    state: "present"
    name: "{{ item }}"

- name: "Set mail location to \"~/Maildir\""
  lineinfile:
    path: "/etc/dovecot/conf.d/10-mail.conf"
    regexp: "^#?mail_location ="
    line: "mail_location = maildir:~/Maildir"
    state: present
  notify: "reload dovecot"

- name: "Apply lda configuration"
  template:
    src: "15-lda.conf.j2"
    dest: "/etc/dovecot/conf.d/15-lda.conf"
  notify: "reload dovecot"
    
- name: "Apply ssl configuration"
  template:
    src: "10-ssl.conf.j2"
    dest: "/etc/dovecot/conf.d/10-ssl.conf"
  notify: "reload dovecot"

- name: "Apply auth configuration"
  template:
    src: "10-auth.conf"
    dest: "/etc/dovecot/conf.d/10-auth.conf"
  notify: "reload dovecot"

- name: "Apply master configuration"
  template:
    src: "10-master.conf"
    dest: "/etc/dovecot/conf.d/10-master.conf"
  notify: "reload dovecot"

- name: "Open port 993 in firewall"
  firewalld:
    service: "imaps"
    state: enabled
    immediate: yes
    permanent: yes

- name: "Enable and start dovecot"
  service:
    name: "dovecot"
    state: "started"
    enabled: yes
