---

- name: "Install dovecot and pigeonhole packages"
  loop:
    - dovecot
    - dovecot-pigeonhole
  package:
    state: "present"
    name: "{{ item }}"

# TODO loop the configuration installs

- name: "Set mail location to \"~/Maildir\""
  copy:
    dest: "/etc/dovecot/conf.d/10-mail.conf"
    src: "dovecot/10-mail.conf"
  notify: "reload dovecot"

- name: "Apply lda configuration"
  template:
    src: "dovecot/15-lda.conf.j2"
    dest: "/etc/dovecot/conf.d/15-lda.conf"
  notify: "reload dovecot"
    
- name: "Apply ssl configuration"
  template:
    src: "dovecot/10-ssl.conf.j2"
    dest: "/etc/dovecot/conf.d/10-ssl.conf"
  notify: "reload dovecot"

- name: "Apply auth configuration"
  copy:
    src: "dovecot/10-auth.conf"
    dest: "/etc/dovecot/conf.d/10-auth.conf"
  notify: "reload dovecot"

- name: "Apply master configuration"
  copy:
    src: "dovecot/10-master.conf"
    dest: "/etc/dovecot/conf.d/10-master.conf"
  notify: "reload dovecot"

- name: "Apply sieve configuration"
  copy:
    src: "dovecot/90-sieve.conf"
    dest: "/etc/dovecot/conf.d/90-sieve.conf"
  notify: "reload dovecot"

- name: "Create sieve-after directory"
  file:
    path: "/etc/dovecot/sieve-after"
    state: "directory"

- name: "Apply spam configuration"
  copy:
    src: "dovecot/spam-to-folder.sieve"
    dest: "/etc/dovecot/sieve-after/spam-to-folder.sieve"

- name: "Compile spam configuration"
  shell: "sievec /etc/dovecot/sieve-after/spam-to-folder.sieve"
  notify: "reload dovecot"

- name: "Open port 993 in firewall"
  firewalld:
    service: "imaps"
    state: enabled
    immediate: yes
    permanent: yes

- name: "Enable and start dovecot"
  service:
    name: "dovecot"
    state: "started"
    enabled: yes
