---

- name: "Install opendkim, spamassassin, clamav"
  loop:
    - opendkim
    - spamassassin
    - clamav
  package:
    state: "present"
    name: "{{ item }}"

- name: "Check if a dkim key is already existing"
  stat:
    path: "/etc/opendkim/keys/{{ mail.{{ domains[0].main }}.private"
  register: keycheck_result

- name: "Generate dkim key pair"
  shell: "/sbin/opendkim-genkey -r -h sha256 -D /etc/opendkim/keys/ -d mail.{{ domains[0].main }} -s mail.{{ domains[0].main }}"
  when: keycheck_result.stat.exists == false

- name: "Add key to KeyTable"
  lineinfile:
    path: "/etc/opendkim/KeyTable"
    regexp: ":mail:"
    line: "mail.{{ domains[0].main }} mail.{{ domains[0].main }}:mail:/etc/opendkim/keys/mail.{{ domains[0].main }}.private"
    state: "present"
  notify: "restart opendkim"

- name: ""

- name: "Apply postfix main configuration"
  template:
    src: "main.cf.j2"
    dest: "/etc/postfix/main.cf"
    owner: "root"
    group: "root"
  notify: "restart opendkim"

- name: "Copy postfix master configuration"
  template:
    src: "master.cf"
    dest: "/etc/postfix/master.cf"
    owner: "root"
    group: "root"
  notify: "reload postfix"

- name: "Open port 587 and 25 in firewall"
  loop:
    - "smtp"
    - "smtp-submission"
  firewalld:
    service: "{{ item }}"
    state: enabled
    immediate: yes
    permanent: yes

- name: "Enable and start postfix"
  service:
    name: "postfix"
    state: "started"
    enabled: yes
