---

- name: "Install opendmarc"
  package:
    name: "opendmarc"
    state: "present"

- name: "Copy opendmarc configuration"
  template:
    src: "opendmarc.conf.j2"
    dest: "/etc/opendmarc.conf"
  notify: "restart opendmarc"

- name: "Create dir for opendmarc service configuration"
  file:
    path: "/etc/systemd/system/opendmarc.service.d/"
    state: "directory"

- name: "Apply systemd opendmarc configuration"
  copy:
    src: "service-chgrp.conf"
    dest: "/etc/systemd/system/opendmarc.service.d/change_group.conf"
  notify:
    - "systemd reload config"
    - "restart opendmarc"

- name: "Enable and start opendmarc"
  service:
    name: "opendmarc"
    state: "started"
    enabled: yes
