---

- name: "Install opendmarc"
  package:
    state: "present"
    name: "opendmarc"

- name: "Copy opendmarc configuration"
  template:
    src: "opendmarc.conf.j2"
    dest: "/etc/opendmarc.conf"
    owner: "root"
    group: "root"
  notify: "restart opendmarc"

- name: "Enable and start opendmarc"
  service:
    name: "opendmarc"
    state: "started"
    enabled: yes
