---

- name: "Install postfix and mailx packages"
  loop:
    - postfix
    - mailx
  package:
    state: "present"
    name: "{{ item }}"

- name: "Redirect root mails to {{ username_on_remote.stdout }}"
  lineinfile:
    path: "/etc/aliases"
    regexp: "^#?root:.*"
    line: "root:\t\t{{ username_on_remote.stdout }}"
    state: "present"
  notify: "newaliases"

- name: "Init aliases list with root's redirection"
  set_fact:
    aliases_string: "{{ 'root: ' ~ rootmail_user ~ '\n' }}"
  vars:
    rootmail_user: "{{ (users | selectattr('is_admin') | first ).login }}"

- name: "test alias string generation"
  set_fact:
    aliases_string: "{{ aliases_string ~ item.1 ~ ': ' ~ item.0.login ~ '\n' }}"
  loop: "{{ users | subelements('aliases', skip_missing=true) }}"

- name: "Apply aliases list to /etc/aliases"
  blockinfile:
    block: "{{ aliases_string }}"
    path: "/etc/aliases"
    marker: "# {mark} USER-DEFINED ALIASES"
  notify: "newaliases"

- name: "Apply postfix main configuration"
  template:
    src: "postfix/main.cf.j2"
    dest: "/etc/postfix/main.cf"
  notify: "reload postfix"

- name: "Copy postfix master configuration"
  copy:
    src: "postfix/master.cf"
    dest: "/etc/postfix/master.cf"
  notify: "reload postfix"

- name: "Open port 587 and 25 in firewall"
  loop:
    - "smtp"
    - "smtp-submission"
  firewalld:
    service: "{{ item }}"
    state: "enabled"
    immediate: yes
    permanent: yes

- name: "Enable and start postfix"
  service:
    name: "postfix"
    state: "started"
    enabled: yes
