---

- name: "Install postfix and mailx packages"
  loop:
    - postfix
    - mailx
  package:
    state: "present"
    name: "{{ item }}"

- name: "Init aliases list with root's redirection"
  set_fact:
    aliases_string: "{{ 'root: ' ~ rootmail_user ~ '\n' }}"
  vars:
    rootmail_user: "{{ (users | selectattr('is_admin') | first ).login }}"

- name: "Init login map with root's mapping"
  set_fact:
    senders_string: "{{ 'root ' ~ item.login ~ '\n' }}"
  loop: "{{ users | selectattr('is_admin') | list }}"

- name: "Add users in senders map"
  set_fact:
    senders_string: "{{ senders_string ~ item.login ~ ' ' ~ item.login ~ '\n' }}"
  loop: "{{ users }}"

- name: "Add user-defined aliases to aliases list and senders map"
  set_fact:
    aliases_string: "{{ aliases_string ~ item.1 ~ ': ' ~ item.0.login ~ '\n' }}"
    senders_string: "{{ senders_string ~ item.1 ~ ' ' ~ item.0.login ~ '\n' }}"
  loop: "{{ users | subelements('aliases', skip_missing=true) }}"

- name: "Apply aliases list to /etc/aliases"
  blockinfile:
    block: "{{ aliases_string }}"
    path: "/etc/aliases"
    marker: "# {mark} USER-DEFINED ALIASES"
  notify: "newaliases"

- name: "Apply login map to /etc/postfix/sender_login_map"
  blockinfile:
    create: yes
    block: "{{ senders_string }}"
    path: "/etc/postfix/sender_login_map"
    marker: "# {mark} USER-DEFINED SENDERS"
  notify: "postmap"

- name: "Apply postfix main configuration"
  template:
    src: "postfix/main.cf.j2"
    dest: "/etc/postfix/main.cf"
  notify: "reload postfix"

- name: "Copy postfix master configuration"
  copy:
    src: "postfix/master.cf"
    dest: "/etc/postfix/master.cf"
  notify: "reload postfix"

- name: "Apply certbot --deploy-hook to reload postfix"
  copy:
    src: "postfix/certbot.deploy-hook.sh"
    dest: "/etc/letsencrypt/renewal-hooks/deploy/020_postfix-reload"


# TODO think about switching to smtps / tcp :465, considered to be the "new standard", which should have always been cause starttls is so vulnerable to mitm attacks...

- name: "Open port 587 and 25 in firewall"
  loop:
    - "smtp"
    - "smtp-submission"
  firewalld:
    service: "{{ item }}"
    state: "enabled"
    immediate: yes
    permanent: yes

- name: "Enable and start postfix"
  service:
    name: "postfix"
    state: "started"
    enabled: yes
