---

- name: "Install spamassassin"
  loop:
    - "spamassassin"
    - "spamass-milter"
  package:
    name: "{{ item }}"
    state: "present"

- name: "Append mail group to sa-milt user"
  user:
    name: "sa-milt"
    groups: "mail"
    append: yes

- name: "Copy spamass-milter sysconfig"
  copy:
    src: "spamassassin/spamass-milter"
    dest: "/etc/sysconfig/spamass-milter"
  notify: "restart spamass-milter"

- name: "Enable and start spamass-milter"
  service:
    name: "spamass-milter"
    state: "started"
    enabled: yes
  notify: "update spam rules"
