---

version: "3"
services:
  jenkins:
    build:
      context: "https://github.com/jenkinsci/docker.git"
      dockerfile: "Dockerfile-alpine"
    image: "jenkins:alpine"
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    restart: "always"

volumes:
  jenkins-data:
