---

- name: "Check different ssh port and take appropriate measures"
  import_tasks: "check_ports.yml"
  tags: ['always', 'checkport']

- name: "Gather facts"
  setup:

####
# note:
# this block has to be executed in one go or the server won't be accessible
# from ssh to continue
#

- name: "Set up ssh"
  import_tasks: "ssh.yml"
  tags: ['ssh']

- name: "Set up unix users"
  import_tasks: "users.yml"
  tags: ['users']

- meta: flush_handlers

- name: "Forgetting root ssh connection"
  when: use_ssh_root is defined and use_ssh_root
  set_fact:
    ansible_port: "{{ target_ssh_port }}"
    ansible_user: "{{ target_ssh_user }}"

- name: "Pause to let the time to disable firewalls"
  when: use_ssh_root is defined and use_ssh_root
  pause:

#
####

- name: "Install utilities"
  import_tasks: "utils.yml"
  tags: ['utils']

- name: "Update system"
  import_tasks: "update.yml"
  tags: ['update']

