---

- name: "Reboot command"
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

# check if machine is waiting for luks decryption
- name: "Check port 222"
  wait_for:
    port: "222"
    state: "started"
    host: "{{ ansible_host }}"
    connect_timeout: "5"
    timeout: "40"
  ignore_errors: yes
  delegate_to: "localhost"
  register: checkDropbear_result

- block:        
    - name: "Prepare to decrypt luks devices"
      set_fact:
        is_waiting_decrypt: yes
        target_ssh_port: "{{ target_ssh_port }}"
        target_ssh_user: "{{ target_ssh_user }}"
        target_ssh_use_tty: "{{ target_ssh_use_tty }}"
        target_ssh_host_key_checking: "{{ target_ssh_host_key_checking }}"
        ansible_port: 222
        ansible_user: "root"
        ansible_ssh_use_tty: no
        ansible_ssh_host_key_checking: no
    
    - name: "Unlock luks devices"
      raw: "unlock <<< {{ host_passwords.luks_passphrase | quote }}"
      ignore_errors: yes
    
    - name: "Reset ssh port to {{ target_ssh_port }}"
      set_fact:
        ansible_port: "{{ target_ssh_port }}"
        ansible_user: "{{ target_ssh_user }}"
        ansible_ssh_use_tty: "{{ target_ssh_use_tty }}"
        ansible_ssh_host_key_checking: "{{ target_ssh_host_key_checking }}"
    
    # Wait until machine has finished booting
    - name: "Check port {{ ansible_port }}"
      wait_for:
        port: "{{ ansible_port }}"
        state: "started"
        host: "{{ ansible_host }}"
        connect_timeout: "5"
        timeout: "20"
      delegate_to: "localhost"
    
  when:
    - checkDropbear_result is defined
    - checkDropbear_result.state is defined
