---

- name: "Apply sshd_config"
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
  notify: "reload sshd"

- name: "Add ssh port {{ target_ssh_port }} in selinux policy"
  seport:
    setype: "ssh_port_t"
    ports: "{{ target_ssh_port }}"
    proto: "tcp"
    state: "present"

- name: "Add ssh port {{ target_ssh_port }} in firewalld policy"
  command: "firewall-cmd --permanent --service=ssh --{{ item.state }}-port={{ item.port }}"
  loop:
    - { port: "{{ target_ssh_port }}/tcp", state: "add" }
    - { port: "22/tcp", state: "remove" }
  notify: "reload firewalld"
