---

# this tasks doesn't take care of old user cleanups
#   (because I have no need for such functionnality atm)

- name: "Set users"
  loop: "{{ users }}"
  user:
    name: "{{ item.login }}"
    groups: "{{ 'wheel' if item.is_admin is defined and item.is_admin }}"
    comment: "{{ item.fullname }}"
    password: "{{ item.password }}"
    shell: "{{ item.shell | default('/sbin/nologin', true) }}"
    
- name: "Deploy ssh key for each user"
  loop: "{{ users | selectattr('pubkeys', 'string') | list }}"
  authorized_key:
    user: "{{ item.login }}"
    key: "{{ item.pubkeys }}"
    exclusive: yes

- name: "Deploy ssh keys for root user"
  authorized_key:
    user: "root"
    key: "{{ users | selectattr('is_admin') | map(attribute='pubkeys') | join(\"\n\") }}"
    exclusive: yes
  notify: "build initramfs"
