---

# TODO add dracut-crypt-ssh repo

- name: "Install/update packages"
  package:
    name: "{{ item }}"
    state: "present"
  loop:
    - "epel-release"
    - "dracut-crypt-ssh"
    - "vim"
    - "screen"
    - "bash-completion"
    - "rsync"
