---

- name: "Set up extra repositories"
  yum_repository:
    name: "gsauthof-dracut-sshd"
    file: "gsauthof-dracut-sshd-epel-8"
    baseurl: "https://copr-be.cloud.fedoraproject.org/results/gsauthof/dracut-sshd/epel-8-$basearch/"
    description: "Copr repo for dracut-sshd owned by gsauthof"
    enabled: yes
    gpgcheck: yes
    skip_if_unavailable: yes

- name: "Install/update packages"
  yum:
    name: "{{ item }}"
    state: "present"
  loop:
    - "epel-release"
    - "dracut-sshd"
    - "vim"
    - "screen"
    - "bash-completion"
    - "rsync"
    - "git"
