---

- name: "build initramfs"
  shell: "dracut --force"

- name: "import reboot handlers"
  import_tasks: "reboot.yml"
  listen: "reboot"

- name: "restart services"
  loop: "{{ services_to_restart.stdout_lines }}"
  service:
    name: "{{ item }}"
    state: "restarted"

- name: "reload sshd"
  service:
    name: "sshd"
    state: "reloaded"

- name: "reload firewalld"
  service:
    name: "firewalld"
    state: "reloaded"
