---

- name: "reboot"
  reboot:

- name: "restart services"
  loop: "{{ services_to_restart.stdout_lines }}"
  service:
    name: "{{ item }}"
    state: "restarted"

- name: "reload sshd"
  service:
    name: "sshd"
    state: "reloaded"

- name: "reload firewalld"
  service:
    name: "firewalld"
    state: "reloaded"
