---

- name: "build initramfs"
  shell: "dracut --force"

- name: "reboot"
  include_tasks: "reboot.yml"

- name: "restart services"
  loop: "{{ services_to_restart.stdout_lines }}"
  service:
    name: "{{ item }}"
    state: "restarted"

- name: "reload sshd"
  service:
    name: "sshd"
    state: "reloaded"

- name: "reload firewalld"
  service:
    name: "firewalld"
    state: "reloaded"

- name: "reload tmpfiles"
  shell: "systemd-tmpfiles --create --remove"

- name: "reload fail2ban"
  service:
    name: "fail2ban"
    state: "reloaded"
