---
#
# host_passwords:
#   root: "root-password"
#   grub: "grub-password"
#   nx_admin: "nx_admin-password"

host_passwords:
  root: "{{ vault_host_passwords.root }}"
  grub: "{{ vault_host_passwords.grub }}"
  nx_admin: "{{ vault_host_passwords.nx_admin }}"
