---
all:
  vars:

    # do not actually request tls certificates
    #tls_dry_run: "yes"

  children:
    docker-masters:
      hosts:
        dock-master:

  hosts:
    dock-master:
      ansible_host: "dock-master.kingdom"
